# Generated by Django 4.2.5 on 2024-01-17 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("team", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=50)),
                ("contacts", models.CharField(blank=True, max_length=255)),
                ("country_flag", models.CharField(max_length=20)),
                ("official_team_name", models.CharField(max_length=200)),
                ("member_since", models.DateField()),
            ],
            options={
                "db_table": "Teams",
            },
        ),
    ]
